/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.swigtest.core;

public class SwigCoreParams {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SwigCoreParams(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SwigCoreParams obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swig_testJNI.delete_SwigCoreParams(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMin_lat(double value) {
    swig_testJNI.SwigCoreParams_min_lat_set(swigCPtr, this, value);
  }

  public double getMin_lat() {
    return swig_testJNI.SwigCoreParams_min_lat_get(swigCPtr, this);
  }

  public void setMax_lat(double value) {
    swig_testJNI.SwigCoreParams_max_lat_set(swigCPtr, this, value);
  }

  public double getMax_lat() {
    return swig_testJNI.SwigCoreParams_max_lat_get(swigCPtr, this);
  }

  public void setMin_lng(double value) {
    swig_testJNI.SwigCoreParams_min_lng_set(swigCPtr, this, value);
  }

  public double getMin_lng() {
    return swig_testJNI.SwigCoreParams_min_lng_get(swigCPtr, this);
  }

  public void setMax_lng(double value) {
    swig_testJNI.SwigCoreParams_max_lng_set(swigCPtr, this, value);
  }

  public double getMax_lng() {
    return swig_testJNI.SwigCoreParams_max_lng_get(swigCPtr, this);
  }

  public void setTime_point_type(int value) {
    swig_testJNI.SwigCoreParams_time_point_type_set(swigCPtr, this, value);
  }

  public int getTime_point_type() {
    return swig_testJNI.SwigCoreParams_time_point_type_get(swigCPtr, this);
  }

  public void setPassenger_state_filter(int value) {
    swig_testJNI.SwigCoreParams_passenger_state_filter_set(swigCPtr, this, value);
  }

  public int getPassenger_state_filter() {
    return swig_testJNI.SwigCoreParams_passenger_state_filter_get(swigCPtr, this);
  }

  public void setFcd_gps_order_by_devid(boolean value) {
    swig_testJNI.SwigCoreParams_fcd_gps_order_by_devid_set(swigCPtr, this, value);
  }

  public boolean getFcd_gps_order_by_devid() {
    return swig_testJNI.SwigCoreParams_fcd_gps_order_by_devid_get(swigCPtr, this);
  }

  public SwigCoreParams() {
    this(swig_testJNI.new_SwigCoreParams(), true);
  }

}
