/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.swigtest.core;

public class SwigCorePointVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SwigCorePointVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SwigCorePointVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swig_testJNI.delete_SwigCorePointVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SwigCorePointVector() {
    this(swig_testJNI.new_SwigCorePointVector(), true);
  }

  public boolean empty() {
    return swig_testJNI.SwigCorePointVector_empty(swigCPtr, this);
  }

  public int size() {
    return swig_testJNI.SwigCorePointVector_size(swigCPtr, this);
  }

  public void reserve(int n) {
    swig_testJNI.SwigCorePointVector_reserve(swigCPtr, this, n);
  }

  public void clear() {
    swig_testJNI.SwigCorePointVector_clear(swigCPtr, this);
  }

  public void add(SwigCorePoint fcd_point) {
    swig_testJNI.SwigCorePointVector_add(swigCPtr, this, SwigCorePoint.getCPtr(fcd_point), fcd_point);
  }

  public SwigCorePoint get(int i) {
    return new SwigCorePoint(swig_testJNI.SwigCorePointVector_get(swigCPtr, this, i), false);
  }

  public SWIGTYPE_p_std__vectorT_SwigCorePoint_t data() {
    return new SWIGTYPE_p_std__vectorT_SwigCorePoint_t(swig_testJNI.SwigCorePointVector_data(swigCPtr, this), false);
  }

}
