/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.swigtest.core;

public class swig_testJNI {
  public final static native void SwigCoreParams_min_lat_set(long jarg1, SwigCoreParams jarg1_, double jarg2);
  public final static native double SwigCoreParams_min_lat_get(long jarg1, SwigCoreParams jarg1_);
  public final static native void SwigCoreParams_max_lat_set(long jarg1, SwigCoreParams jarg1_, double jarg2);
  public final static native double SwigCoreParams_max_lat_get(long jarg1, SwigCoreParams jarg1_);
  public final static native void SwigCoreParams_min_lng_set(long jarg1, SwigCoreParams jarg1_, double jarg2);
  public final static native double SwigCoreParams_min_lng_get(long jarg1, SwigCoreParams jarg1_);
  public final static native void SwigCoreParams_max_lng_set(long jarg1, SwigCoreParams jarg1_, double jarg2);
  public final static native double SwigCoreParams_max_lng_get(long jarg1, SwigCoreParams jarg1_);
  public final static native void SwigCoreParams_time_point_type_set(long jarg1, SwigCoreParams jarg1_, int jarg2);
  public final static native int SwigCoreParams_time_point_type_get(long jarg1, SwigCoreParams jarg1_);
  public final static native void SwigCoreParams_passenger_state_filter_set(long jarg1, SwigCoreParams jarg1_, int jarg2);
  public final static native int SwigCoreParams_passenger_state_filter_get(long jarg1, SwigCoreParams jarg1_);
  public final static native void SwigCoreParams_fcd_gps_order_by_devid_set(long jarg1, SwigCoreParams jarg1_, boolean jarg2);
  public final static native boolean SwigCoreParams_fcd_gps_order_by_devid_get(long jarg1, SwigCoreParams jarg1_);
  public final static native long new_SwigCoreParams();
  public final static native void delete_SwigCoreParams(long jarg1);
  public final static native long new_SwigCorePoint();
  public final static native void delete_SwigCorePoint(long jarg1);
  public final static native void SwigCorePoint_SetMembers(long jarg1, SwigCorePoint jarg1_, long jarg2, double jarg3, double jarg4, float jarg5, long jarg6, short jarg7, short jarg8);
  public final static native void SwigCorePoint_dev_id_set(long jarg1, SwigCorePoint jarg1_, long jarg2);
  public final static native long SwigCorePoint_dev_id_get(long jarg1, SwigCorePoint jarg1_);
  public final static native void SwigCorePoint_lat_set(long jarg1, SwigCorePoint jarg1_, double jarg2);
  public final static native double SwigCorePoint_lat_get(long jarg1, SwigCorePoint jarg1_);
  public final static native void SwigCorePoint_lng_set(long jarg1, SwigCorePoint jarg1_, double jarg2);
  public final static native double SwigCorePoint_lng_get(long jarg1, SwigCorePoint jarg1_);
  public final static native void SwigCorePoint_speed_set(long jarg1, SwigCorePoint jarg1_, float jarg2);
  public final static native float SwigCorePoint_speed_get(long jarg1, SwigCorePoint jarg1_);
  public final static native void SwigCorePoint_gps_time_set(long jarg1, SwigCorePoint jarg1_, long jarg2);
  public final static native long SwigCorePoint_gps_time_get(long jarg1, SwigCorePoint jarg1_);
  public final static native void SwigCorePoint_heading_set(long jarg1, SwigCorePoint jarg1_, short jarg2);
  public final static native short SwigCorePoint_heading_get(long jarg1, SwigCorePoint jarg1_);
  public final static native void SwigCorePoint_passenger_state_set(long jarg1, SwigCorePoint jarg1_, short jarg2);
  public final static native short SwigCorePoint_passenger_state_get(long jarg1, SwigCorePoint jarg1_);
  public final static native long new_SwigCorePointVector();
  public final static native void delete_SwigCorePointVector(long jarg1);
  public final static native boolean SwigCorePointVector_empty(long jarg1, SwigCorePointVector jarg1_);
  public final static native int SwigCorePointVector_size(long jarg1, SwigCorePointVector jarg1_);
  public final static native void SwigCorePointVector_reserve(long jarg1, SwigCorePointVector jarg1_, int jarg2);
  public final static native void SwigCorePointVector_clear(long jarg1, SwigCorePointVector jarg1_);
  public final static native void SwigCorePointVector_add(long jarg1, SwigCorePointVector jarg1_, long jarg2, SwigCorePoint jarg2_);
  public final static native long SwigCorePointVector_get(long jarg1, SwigCorePointVector jarg1_, int jarg2);
  public final static native long SwigCorePointVector_data(long jarg1, SwigCorePointVector jarg1_);
  public final static native long new_SwigTestCore();
  public final static native void delete_SwigTestCore(long jarg1);
  public final static native boolean SwigTestCore_Init(long jarg1, SwigTestCore jarg1_, long jarg2, SwigCoreParams jarg2_, long jarg3, long jarg4, long jarg5);
  public final static native boolean SwigTestCore_OnFcdData(long jarg1, SwigTestCore jarg1_, long jarg2, SwigCorePointVector jarg2_);
  public final static native long SwigTestCore_GetErrorStr(long jarg1, SwigTestCore jarg1_);
  public final static native void SwigTestCore_Reset(long jarg1, SwigTestCore jarg1_);
}
