/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.swigtest;

public class SwigCorePoint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SwigCorePoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SwigCorePoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swig_testJNI.delete_SwigCorePoint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SwigCorePoint() {
    this(swig_testJNI.new_SwigCorePoint(), true);
  }

  public void SetMembers(SWIGTYPE_p_std__string dev_id, double lat, double lng, float speed, SWIGTYPE_p_std__string gps_time, short heading, short passenger_state) {
    swig_testJNI.SwigCorePoint_SetMembers(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(dev_id), lat, lng, speed, SWIGTYPE_p_std__string.getCPtr(gps_time), heading, passenger_state);
  }

  public void setDev_id(SWIGTYPE_p_std__string value) {
    swig_testJNI.SwigCorePoint_dev_id_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getDev_id() {
    return new SWIGTYPE_p_std__string(swig_testJNI.SwigCorePoint_dev_id_get(swigCPtr, this), true);
  }

  public void setLat(double value) {
    swig_testJNI.SwigCorePoint_lat_set(swigCPtr, this, value);
  }

  public double getLat() {
    return swig_testJNI.SwigCorePoint_lat_get(swigCPtr, this);
  }

  public void setLng(double value) {
    swig_testJNI.SwigCorePoint_lng_set(swigCPtr, this, value);
  }

  public double getLng() {
    return swig_testJNI.SwigCorePoint_lng_get(swigCPtr, this);
  }

  public void setSpeed(float value) {
    swig_testJNI.SwigCorePoint_speed_set(swigCPtr, this, value);
  }

  public float getSpeed() {
    return swig_testJNI.SwigCorePoint_speed_get(swigCPtr, this);
  }

  public void setGps_time(SWIGTYPE_p_std__string value) {
    swig_testJNI.SwigCorePoint_gps_time_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getGps_time() {
    return new SWIGTYPE_p_std__string(swig_testJNI.SwigCorePoint_gps_time_get(swigCPtr, this), true);
  }

  public void setHeading(short value) {
    swig_testJNI.SwigCorePoint_heading_set(swigCPtr, this, value);
  }

  public short getHeading() {
    return swig_testJNI.SwigCorePoint_heading_get(swigCPtr, this);
  }

  public void setPassenger_state(short value) {
    swig_testJNI.SwigCorePoint_passenger_state_set(swigCPtr, this, value);
  }

  public short getPassenger_state() {
    return swig_testJNI.SwigCorePoint_passenger_state_get(swigCPtr, this);
  }

}
