/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.swigtest;

public class SwigTestCore {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SwigTestCore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SwigTestCore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swig_testJNI.delete_SwigTestCore(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SwigTestCore() {
    this(swig_testJNI.new_SwigTestCore(), true);
  }

  public boolean Init(SwigCoreParams params, String segments_csv, String seg_edges_csv, String ex_routes_csv) {
    return swig_testJNI.SwigTestCore_Init(swigCPtr, this, SwigCoreParams.getCPtr(params), params, segments_csv, seg_edges_csv, ex_routes_csv);
  }

  public boolean OnFcdData(SwigCorePointVector fcd_points) {
    return swig_testJNI.SwigTestCore_OnFcdData(swigCPtr, this, SwigCorePointVector.getCPtr(fcd_points), fcd_points);
  }

  public String GetErrorStr() {
    return swig_testJNI.SwigTestCore_GetErrorStr(swigCPtr, this);
  }

  public void Reset() {
    swig_testJNI.SwigTestCore_Reset(swigCPtr, this);
  }

}
